
name: kitchen

## Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:  
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: samjithin/kitchen:latest
    
    

    steps:
      
      - uses: actions/checkout@v2

      
        
      - name: connect with GCP
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
        
      # Run Kitchen tests 
      - name: kitchen-testing
        run : |
        
          kitchen create
          kitchen converge
          kitchen list
          kitchen verify 
          kitchen destroy


      - name: kitchen-destroy
        if: ${{ failure() }}
        run: |   
          kitchen destroy

